version: '3'
services:
  jupyterlab:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/home/work"
    ports:
      - "8888:8888"
    command : jupyter lab --ip=0.0.0.0 --port 8888 --allow-root --notebook-dir=/home/work --LabApp.token=''